accessControl:
  salt: kCE8kecDobDPutK0NI1LXsgTcIFgkUSZ
api:
  key: 79399C733DC74CCEA0EA2A57FE120EC8
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1500983100
      _important:
        read_until: 1478614200
      _octopi:
        read_until: 1499253000
      _plugins:
        read_until: 1500768000
      _releases:
        read_until: 1501158300
  discovery:
    upnpUuid: 9537c40b-92af-4359-bcf3-e54fbcb4c3f3
  softwareupdate:
    _config_version: 5
printerProfiles:
  default: _default
server:
  firstRun: false
  secretKey: qB1fQL4eq4yyqOC9czeDis6TeEfqIVBB
  seenWizards:
    corewizard: null
    cura: null
    softwareupdate: null
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://10.19.0.85:8090/?action=snapshot
  stream: http://10.19.0.85:8090/?action=stream

# Settings only relevant for development
devel:

  # Settings for the virtual printer
  virtualPrinter:

    # Whether to enable the virtual printer and include it in the list of available serial connections.
    # Defaults to false.
    enabled: true

    # Whether to send an additional "ok" after a resend request (like Repetier)
    okAfterResend: false

    # Whether to force checksums and line number in the communication (like Repetier), if set to true 
    # printer will only accept commands that come with linenumber and checksum and throw an error for
    # lines that don't. Defaults to false
    forceChecksum: false

    # Whether to send "ok" responses with the line number that gets acknowledged by the "ok". Defaults
    # to false.
    okWithLinenumber: false

